import sys
import re

def convert_md_to_html(line, ordered_list, unordered_list):
    close_ordered = ""
    close_unordered = ""

    # ... (código existente)

    return line, close_ordered, close_unordered, ordered_list, unordered_list

def generate_html(input_filename):
    output_filename = "output.html"

    try:
        with open(input_filename, "r") as md_file, open(output_filename, "w") as html_file:
            lines = md_file.readlines()

            pre_html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <title>{input_filename}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
'''

            pos_html = '''
</body>
<h5>Generated by Markdown to HTML Converter</h5>
</html>
'''

            ordered_list = False
            unordered_list = False
            content = ''

            for line in lines:
                new_line, close_ordered, close_unordered, ordered_list, unordered_list = convert_md_to_html(
                    line, ordered_list, unordered_list)

                if new_line == line and line != "\n":
                    new_line = f"<p>{line.strip()}</p>\n"

                content += f"    {close_ordered}{close_unordered}{new_line}"

            if ordered_list:
                content += '</ol>\n'

            if unordered_list:
                content += '</ul>\n'

            full_html = pre_html + content + pos_html
            html_file.write(full_html)

        print("HTML file generated successfully")

    except FileNotFoundError:
        print(f"Error: File '{input_filename}' not found.")
        sys.exit(1)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: python3 script.py <input.md>")
        sys.exit(1)

    input_file = sys.argv[1]
    generate_html(input_file)